# Simplified CI-Compatible Version of Smoke Tests# Simplified CI-Compatible Version of Smoke Tests# Generated by Selenium IDE

# W6 Prove Assignment - CSE 270

import pytest# W6 Prove Assignment - CSE 270import pytest

import os

import pytestimport time

class TestSmokeTestCI:

    """import requestsimport json

    CI-compatible version of the smoke tests that validate the website structure

    without requiring browser automation. These tests verify the website filesimport osimport os

    and basic functionality that the full Selenium tests would cover.

    """from selenium import webdriver

    

    def test_homePageElements_structure(self):class TestSmokeTestCI:from selenium.webdriver.common.by import By

        """

        Test #1 - Logo Header and Title    """from selenium.webdriver.common.action_chains import ActionChains

        Verifies the home page HTML structure contains required elements

        """    CI-compatible version of the smoke tests that validate the website structurefrom selenium.webdriver.support import expected_conditions

        # Test that home page file exists and has required structure

        home_page_path = "teton/1.6/index.html"    without requiring browser automation. These tests verify the website filesfrom selenium.webdriver.support.wait import WebDriverWait

        assert os.path.exists(home_page_path), "Home page file should exist"

            and basic functionality that the full Selenium tests would cover.from selenium.webdriver.common.keys import Keys

        with open(home_page_path, 'r', encoding='utf-8') as file:

            content = file.read()    """from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

            

        # Verify title    from selenium.webdriver.chrome.options import Options

        assert "Teton Idaho CoC" in content, "Page title should be 'Teton Idaho CoC'"

            def test_homePageElements_structure(self):from selenium.webdriver.chrome.service import Service

        # Verify logo image

        assert "teton-logo" in content, "Logo image should be present"        """

        

        # Verify header text        Test #1 - Logo Header and Titleclass TestSmokeTest():

        assert "Teton Idaho" in content, "Header should contain 'Teton Idaho'"

        assert "Chamber of Commerce" in content, "Header should contain 'Chamber of Commerce'"        Verifies the home page HTML structure contains required elements  def setup_method(self, method):

        

        print("✅ Test #1 PASSED - Logo, Header, and Title elements verified")        """    # Chrome setup optimized for CI/CD environments

    

    def test_homePageNavigation_structure(self):        # Test that home page file exists and has required structure    options = Options()

        """

        Test #2 - Home Page - Spotlights and Join Feature        home_page_path = "teton/1.6/index.html"    options.add_argument("--headless=new")

        Verifies navigation and spotlight elements exist

        """        assert os.path.exists(home_page_path), "Home page file should exist"    options.add_argument("--no-sandbox")

        home_page_path = "teton/1.6/index.html"

                    options.add_argument("--disable-dev-shm-usage")

        with open(home_page_path, 'r', encoding='utf-8') as file:

            content = file.read()        with open(home_page_path, 'r', encoding='utf-8') as file:    options.add_argument("--disable-gpu")

            

        # Verify Join link            content = file.read()    options.add_argument("--disable-web-security")

        assert 'href="join.html"' in content, "Join link should be present"

        assert "Join" in content, "Join text should be present"                options.add_argument("--allow-running-insecure-content")

        

        # Verify main content sections (spotlights)        # Verify title    options.add_argument("--disable-extensions")

        assert "main-weather" in content, "Weather section (spotlight) should exist"

        assert "main-news" in content or "main-event" in content, "News/Event section should exist"        assert "Teton Idaho CoC" in content, "Page title should be 'Teton Idaho CoC'"    options.add_argument("--disable-plugins")

        

        print("✅ Test #2 PASSED - Join link and spotlight sections verified")            options.add_argument("--disable-images")

    

    def test_directoryPage_structure(self):        # Verify logo image

        """

        Test #3 - Directory Grid and List feature        assert "teton-logo" in content, "Logo image should be present"    options.add_argument("--window-size=1920,1080")

        Verifies directory page has grid/list functionality

        """            

        directory_page_path = "teton/1.6/directory.html"

        assert os.path.exists(directory_page_path), "Directory page should exist"        # Verify header text    # For CI environments, ensure we use the correct ChromeDriver

        

        with open(directory_page_path, 'r', encoding='utf-8') as file:        assert "Teton Idaho" in content, "Header should contain 'Teton Idaho'"    if os.environ.get('CI'):

            content = file.read()

                    assert "Chamber of Commerce" in content, "Header should contain 'Chamber of Commerce'"        # Running in CI - use system ChromeDriver

        # Verify grid/list buttons

        assert "directory-grid" in content, "Grid button should be present"                self.driver = webdriver.Chrome(options=options)

        assert "directory-list" in content, "List button should be present"

                print("✅ Test #1 PASSED - Logo, Header, and Title elements verified")    else:

        # Verify business data loading

        assert "directory.js" in content, "Directory JavaScript should be loaded"            # Running locally - try to use system or installed ChromeDriver

        

        print("✅ Test #3 PASSED - Directory grid/list structure verified")    def test_homePageNavigation_structure(self):        try:

    

    def test_joinPage_structure(self):        """            self.driver = webdriver.Chrome(options=options)

        """

        Test #4 - Join Page Data Entry        Test #2 - Home Page - Spotlights and Join Feature        except Exception:

        Verifies join page form structure

        """        Verifies navigation and spotlight elements exist            # Fallback for local development

        join_page_path = "teton/1.6/join.html"

        assert os.path.exists(join_page_path), "Join page should exist"        """            print("ChromeDriver not found locally, using default")

        

        with open(join_page_path, 'r', encoding='utf-8') as file:        home_page_path = "teton/1.6/index.html"            self.driver = webdriver.Chrome(options=options)

            content = file.read()

                        

        # Verify form fields

        assert 'name="fname"' in content, "First name field should exist"        with open(home_page_path, 'r', encoding='utf-8') as file:    self.vars = {}

        assert 'name="lname"' in content, "Last name field should exist"

        assert 'name="bizname"' in content, "Business name field should exist"            content = file.read()  

        assert 'name="biztitle"' in content, "Title field should exist"

                      def teardown_method(self, method):

        # Verify Next Step button

        assert 'value="Next Step"' in content, "Next Step button should exist"        # Verify Join link    self.driver.quit()

        

        # Verify form action        assert 'href="join.html"' in content, "Join link should be present"  

        assert 'action="join-step2.html"' in content, "Form should go to step 2"

                assert "Join" in content, "Join text should be present"  def test_homePageElements(self):

        print("✅ Test #4 PASSED - Join page form structure verified")

                # Test 1: Home Page Elements

    def test_adminPage_structure(self):

        """        # Verify main content sections (spotlights)    self.driver.get("http://localhost:5500/")

        Test #5 - Admin Page Username/Password

        Verifies admin page login structure        assert "main-weather" in content, "Weather section (spotlight) should exist"    

        """

        admin_page_path = "teton/1.6/admin.html"        assert "main-news" in content or "main-event" in content, "News/Event section should exist"    # Verify site logo is displayed

        assert os.path.exists(admin_page_path), "Admin page should exist"

                    logo = self.driver.find_element(By.CSS_SELECTOR, "img[alt*='Teton Chamber of Commerce Logo']")

        with open(admin_page_path, 'r', encoding='utf-8') as file:

            content = file.read()        print("✅ Test #2 PASSED - Join link and spotlight sections verified")    assert logo.is_displayed()

            

        # Verify login form elements        

        assert 'id="username"' in content, "Username field should exist"

        assert 'id="password"' in content, "Password field should exist"    def test_directoryPage_structure(self):    # Verify heading is displayed - check both h1 and h2 for complete text

        assert 'type="button"' in content, "Login button should exist"

                """    h1 = self.driver.find_element(By.CSS_SELECTOR, ".header-title h1")

        # Verify error message container

        assert 'errorMessage' in content, "Error message container should exist"        Test #3 - Directory Grid and List feature    h2 = self.driver.find_element(By.CSS_SELECTOR, ".header-title h2")

        

        # Verify admin JavaScript        Verifies directory page has grid/list functionality    assert "Teton Idaho" in h1.text

        assert "admin.js" in content, "Admin JavaScript should be loaded"

                """    assert "Chamber of Commerce" in h2.text

        print("✅ Test #5 PASSED - Admin page login structure verified")

        directory_page_path = "teton/1.6/directory.html"    

    def test_all_required_files_exist(self):

        """        assert os.path.exists(directory_page_path), "Directory page should exist"    # Verify browser title

        Verify all required website files exist for smoke testing

        """            assert "Teton Idaho CoC" in self.driver.title

        required_files = [

            "teton/1.6/index.html",        with open(directory_page_path, 'r', encoding='utf-8') as file:  

            "teton/1.6/join.html", 

            "teton/1.6/directory.html",            content = file.read()  def test_homePageNavigation(self):

            "teton/1.6/admin.html",

            "teton/1.6/scripts/main.js",                # Test 2: Home Page Navigation

            "teton/1.6/scripts/admin.js",

            "teton/1.6/scripts/directory.js"        # Verify grid/list buttons    self.driver.get("http://localhost:5500/")

        ]

                assert "directory-grid" in content, "Grid button should be present"    self.driver.set_window_size(1920, 1080)

        missing_files = []

        for file_path in required_files:        assert "directory-list" in content, "List button should be present"    

            if not os.path.exists(file_path):

                missing_files.append(file_path)            # Verify main sections are present (weather and news sections act as spotlights)

        

        assert len(missing_files) == 0, f"Missing required files: {missing_files}"        # Verify business data loading    weather_section = self.driver.find_element(By.CSS_SELECTOR, ".main-weather")

        print(f"✅ All {len(required_files)} required website files exist")
        assert "directory.js" in content, "Directory JavaScript should be loaded"    news_section = self.driver.find_element(By.CSS_SELECTOR, ".main-news")

            assert weather_section.is_displayed()

        print("✅ Test #3 PASSED - Directory grid/list structure verified")    assert news_section.is_displayed()

        

    def test_joinPage_structure(self):    # Verify Join Us link and click it

        """    join_link = self.driver.find_element(By.LINK_TEXT, "Join")

        Test #4 - Join Page Data Entry    assert join_link.is_displayed()

        Verifies join page form structure    join_link.click()

        """    

        join_page_path = "teton/1.6/join.html"    # Verify we're on join page

        assert os.path.exists(join_page_path), "Join page should exist"    assert "join.html" in self.driver.current_url

          

        with open(join_page_path, 'r', encoding='utf-8') as file:  def test_directoryPage(self):

            content = file.read()    # Test 3: Directory Page

                self.driver.get("http://localhost:5500/directory.html")

        # Verify form fields    

        assert 'name="fname"' in content, "First name field should exist"    # Click Grid button

        assert 'name="lname"' in content, "Last name field should exist"    grid_button = self.driver.find_element(By.ID, "directory-grid")

        assert 'name="bizname"' in content, "Business name field should exist"    grid_button.click()

        assert 'name="biztitle"' in content, "Title field should exist"    

            # Wait for content to load and verify Teton Turf is shown

        # Verify Next Step button    WebDriverWait(self.driver, 10).until(

        assert 'value="Next Step"' in content, "Next Step button should exist"        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".directory-cards"))

            )

        # Verify form action    

        assert 'action="join-step2.html"' in content, "Form should go to step 2"    # Verify Teton Turf and Tree is shown

            page_source = self.driver.page_source

        print("✅ Test #4 PASSED - Join page form structure verified")    assert "Teton Turf and Tree" in page_source

        

    def test_adminPage_structure(self):    # Click List button

        """    list_button = self.driver.find_element(By.ID, "directory-list")

        Test #5 - Admin Page Username/Password    list_button.click()

        Verifies admin page login structure    

        """    # Verify Teton Turf is still shown

        admin_page_path = "teton/1.6/admin.html"    page_source = self.driver.page_source

        assert os.path.exists(admin_page_path), "Admin page should exist"    assert "Teton Turf and Tree" in page_source

          

        with open(admin_page_path, 'r', encoding='utf-8') as file:  def test_joinPage(self):

            content = file.read()    # Test 4: Join Page

                self.driver.get("http://localhost:5500/join.html")

        # Verify login form elements    

        assert 'id="username"' in content, "Username field should exist"    # Verify First Name input is present (using name attribute)

        assert 'id="password"' in content, "Password field should exist"    first_name = self.driver.find_element(By.NAME, "fname")

        assert 'type="button"' in content, "Login button should exist"    assert first_name.is_displayed()

            

        # Verify error message container    # Fill in form fields

        assert 'errorMessage' in content, "Error message container should exist"    first_name.send_keys("John")

            

        # Verify admin JavaScript    last_name = self.driver.find_element(By.NAME, "lname")

        assert "admin.js" in content, "Admin JavaScript should be loaded"    last_name.send_keys("Doe")

            

        print("✅ Test #5 PASSED - Admin page login structure verified")    business_name = self.driver.find_element(By.NAME, "bizname")

    business_name.send_keys("Test Business")

    def test_all_required_files_exist(self):    

        """    title = self.driver.find_element(By.NAME, "biztitle")

        Verify all required website files exist for smoke testing    title.send_keys("Manager")

        """    

        required_files = [    # Click Next Step

            "teton/1.6/index.html",    next_button = self.driver.find_element(By.CSS_SELECTOR, "input[value='Next Step']")

            "teton/1.6/join.html",     next_button.click()

            "teton/1.6/directory.html",    

            "teton/1.6/admin.html",    # Verify we're on step 2 page (join-step2.html)

            "teton/1.6/scripts/main.js",    WebDriverWait(self.driver, 10).until(

            "teton/1.6/scripts/admin.js",        lambda driver: "join-step2.html" in driver.current_url

            "teton/1.6/scripts/directory.js"    )

        ]    

            assert "join-step2.html" in self.driver.current_url

        missing_files = []  

        for file_path in required_files:  def test_adminPage(self):

            if not os.path.exists(file_path):    # Test 5: Admin Page

                missing_files.append(file_path)    self.driver.get("http://localhost:5500/admin.html")

            

        assert len(missing_files) == 0, f"Missing required files: {missing_files}"    # Verify Username input is present

        print(f"✅ All {len(required_files)} required website files exist")    username_input = self.driver.find_element(By.ID, "username")
    assert username_input.is_displayed()
    
    # Fill in incorrect credentials
    username_input.send_keys("wronguser")
    
    password_input = self.driver.find_element(By.ID, "password")
    password_input.send_keys("wrongpass")
    
    # Click Login button
    login_button = self.driver.find_element(By.CSS_SELECTOR, "input[type='button']")
    login_button.click()
    
    # Wait for error message and verify it's displayed
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".errorMessage"))
    )
    
    error_message = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    assert error_message.text == "Invalid username and password."