# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

class TestSmokeTest():
  def setup_method(self, method):
    # Modified setup for headless Firefox - more reliable in CI/CD
    options = Options()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    
    # Simple Firefox setup - works reliably in CI
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homePageElements(self):
    # Test 1: Home Page Elements
    self.driver.get("http://localhost:5500/")
    
    # Verify site logo is displayed
    logo = self.driver.find_element(By.CSS_SELECTOR, "img[alt*='Teton Chamber of Commerce Logo']")
    assert logo.is_displayed()
    
    # Verify heading is displayed - check both h1 and h2 for complete text
    h1 = self.driver.find_element(By.CSS_SELECTOR, ".header-title h1")
    h2 = self.driver.find_element(By.CSS_SELECTOR, ".header-title h2")
    assert "Teton Idaho" in h1.text
    assert "Chamber of Commerce" in h2.text
    
    # Verify browser title
    assert "Teton Idaho CoC" in self.driver.title
  
  def test_homePageNavigation(self):
    # Test 2: Home Page Navigation
    self.driver.get("http://localhost:5500/")
    self.driver.set_window_size(1920, 1080)
    
    # Verify main sections are present (weather and news sections act as spotlights)
    weather_section = self.driver.find_element(By.CSS_SELECTOR, ".main-weather")
    news_section = self.driver.find_element(By.CSS_SELECTOR, ".main-news")
    assert weather_section.is_displayed()
    assert news_section.is_displayed()
    
    # Verify Join Us link and click it
    join_link = self.driver.find_element(By.LINK_TEXT, "Join")
    assert join_link.is_displayed()
    join_link.click()
    
    # Verify we're on join page
    assert "join.html" in self.driver.current_url
  
  def test_directoryPage(self):
    # Test 3: Directory Page
    self.driver.get("http://localhost:5500/directory.html")
    
    # Click Grid button
    grid_button = self.driver.find_element(By.ID, "directory-grid")
    grid_button.click()
    
    # Wait for content to load and verify Teton Turf is shown
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".directory-cards"))
    )
    
    # Verify Teton Turf and Tree is shown
    page_source = self.driver.page_source
    assert "Teton Turf and Tree" in page_source
    
    # Click List button
    list_button = self.driver.find_element(By.ID, "directory-list")
    list_button.click()
    
    # Verify Teton Turf is still shown
    page_source = self.driver.page_source
    assert "Teton Turf and Tree" in page_source
  
  def test_joinPage(self):
    # Test 4: Join Page
    self.driver.get("http://localhost:5500/join.html")
    
    # Verify First Name input is present (using name attribute)
    first_name = self.driver.find_element(By.NAME, "fname")
    assert first_name.is_displayed()
    
    # Fill in form fields
    first_name.send_keys("John")
    
    last_name = self.driver.find_element(By.NAME, "lname")
    last_name.send_keys("Doe")
    
    business_name = self.driver.find_element(By.NAME, "bizname")
    business_name.send_keys("Test Business")
    
    title = self.driver.find_element(By.NAME, "biztitle")
    title.send_keys("Manager")
    
    # Click Next Step
    next_button = self.driver.find_element(By.CSS_SELECTOR, "input[value='Next Step']")
    next_button.click()
    
    # Verify we're on step 2 page (join-step2.html)
    WebDriverWait(self.driver, 10).until(
        lambda driver: "join-step2.html" in driver.current_url
    )
    
    assert "join-step2.html" in self.driver.current_url
  
  def test_adminPage(self):
    # Test 5: Admin Page
    self.driver.get("http://localhost:5500/admin.html")
    
    # Verify Username input is present
    username_input = self.driver.find_element(By.ID, "username")
    assert username_input.is_displayed()
    
    # Fill in incorrect credentials
    username_input.send_keys("wronguser")
    
    password_input = self.driver.find_element(By.ID, "password")
    password_input.send_keys("wrongpass")
    
    # Click Login button
    login_button = self.driver.find_element(By.CSS_SELECTOR, "input[type='button']")
    login_button.click()
    
    # Wait for error message and verify it's displayed
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".errorMessage"))
    )
    
    error_message = self.driver.find_element(By.CSS_SELECTOR, ".errorMessage")
    assert error_message.text == "Invalid username and password."